name: Compilar Solo Euclides

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4  

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar solo Euclides.java
        run: javac -d out Complejidad/src/Euclides.java


