name: Compilar y Ejecutar Java

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4  

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar el código
        run: javac -d out Cmplejidad/scr/Euclides.java 
      - name: Ejecutar el código
        run: java -cp out Euclides
